<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af8010a1068656c6c6f776f726c642e70726f746f121268656c6c6f776f" .
            "726c645f73657276696365221c0a0c48656c6c6f52657175657374120c0a" .
            "046e616d65180120012809221d0a0a48656c6c6f5265706c79120f0a076d" .
            "65737361676518012001280932590a0747726565746572124e0a08536179" .
            "48656c6c6f12202e68656c6c6f776f726c645f736572766963652e48656c" .
            "6c6f526571756573741a1e2e68656c6c6f776f726c645f73657276696365" .
            "2e48656c6c6f5265706c79220042300a1b696f2e677270632e6578616d70" .
            "6c65732e68656c6c6f776f726c64420f48656c6c6f576f726c6450726f74" .
            "6f5001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

